config/routes.rb
UrlShorts::Application.routes.draw do
  devise_for :users
  resources :urls, only: [:index, :create, :destroy]

  get '/:short' => 'home#go', as: :short

  root 'home#index'

end

app/models/url.rb
require 'autoinc'

class Url
  include Mongoid::Document
  include Mongoid::Autoinc

  field :num_id, type: Integer
  field :original, type: String
  field :clicks, type: Integer, default: 0

  belongs_to :user

  increments :num_id, seed: 1000000

  validates_presence_of :original

  def short
    Url.bijective_encode num_id
  end

  def self.num_id_from_short(s)
    Url.bijective_decode s
  end

  def clicked!
    inc clicks: 1
  end

  ALPHABET =
  "abcdefghijkmnopqrstvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789".split(//)
  # make your own alphabet using:
  # (('a'..'z').to_a + ('A'..'Z').to_a + (0..9).to_a).shuffle.join
 
  def self.bijective_encode(i)
    # from http://refactormycode.com/codes/125-base-62-encoding
    # with only minor modification
    return ALPHABET[0] if i == 0
    s = ''
    base = ALPHABET.length
    while i > 0
      s << ALPHABET[i.modulo(base)]
      i /= base
    end
    s.reverse
  end
   
  def self.bijective_decode(s)
    # based on base2dec() in Tcl translation 
    # at http://rosettacode.org/wiki/Non-decimal_radices/Convert#Ruby
    i = 0
    base = ALPHABET.length
    s.each_char { |c| i = i * base + ALPHABET.index(c) }
    i
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time


  has_many :urls
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  # get /
  def index
    @url = Url.new
  end

  # get /:short[+]
  def go
    short = params[:short]
    info = false

    if short.ends_with? '+'
      info = true
      short.chomp! '+'
    end

    @url = Url.find_by(num_id: Url.num_id_from_short(short)) || not_found

    if info
      render action: 'info'
    else
      @url.clicked!
      redirect_to @url.original
    end
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]

  before_action :set_url, only: [:destroy]

  # GET /urls
  # GET /urls.json
  def index
    if user_signed_in?
      @urls = current_user.urls
    else
      @urls = Url.all
    end
  end

  # POST /urls
  # POST /urls.json
  def create
    @url = Url.new(url_params)

    respond_to do |format|
      @url.user = current_user
      if @url.save
        format.html { redirect_to polymorphic_url([:short], short: "#{@url.short}+"), notice: 'Url was successfully shortened.' }
        format.json { render action: 'show', status: :created, location: @url }
      else
        format.html { render action: 'new' }
        format.json { render json: @url.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    if @url.user.id == current_user.id
      @url.destroy
      respond_to do |format|
        format.html { redirect_to urls_url }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        err = { error: "Can't to delete a url that doesn't belong to you" }
        format.html { redirect_to urls_url, err }
        format.json { render json: err, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_url
      @url = Url.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def url_params
      params.require(:url).permit(:original)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/home/index.html.erb
<div ng-app="Shorts" ng-controller="ShortenUrlCtrl" ng-init="init()">
  <%= form_for(@url, html: {'ng-submit' => 'shorten($event)'}) do |f| %>
    <div class="field">
      <%= f.label :original, 'Your url:' %>
      <%= f.url_field :original, placeholder: 'http://google.com', 'ng-model' => 'original', 'http-prefix' => 'http-prefix', 'required' => 'required', disabled: !user_signed_in? %>
    </div>

    <menu>
      <button type="submit" <%= !user_signed_in? ? 'disabled' : '' %>>Shorten</button>
    </menu>
  <% end %>

  <%
  unless user_signed_in?
  %>
    <div id="needs-login">
      <%= link_to 'Sign up', new_user_registration_path%> or
      <%= link_to 'Login', new_user_session_path %>
      to shorten your urls!
    </div>  
  <%
  end
  %>

  <div id="shortened" ng-show="url">
    <span>Your shortened url:</span>
    <strong>{{url.href}}</strong>
    <a href="{{url.infohref}}">more info</a>
  </div>
</div>

app/views/home/info.html.erb
<p>
  <strong>Original:</strong>
  <%= @url.original %>
</p>

<p>
  <strong>Shortened:</strong>
  <%= polymorphic_url :short %>
  <a href="<%= polymorphic_url :short %>">go</a>
</p>

<p>
  <strong>Clicks:</strong>
  <%= @url.clicks %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Url Shorts</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/angularjs/1.2.6/angular.min.js" %>
  <%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/angularjs/1.2.6/angular-resource.min.js" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <header>
      <h1>
        <a href="/">Url Shorts</a>
      </h1>
      <div id="user">
        <% if user_signed_in? %>
          <span>Logged in as <strong><%= current_user.email %></strong>.</span>
          <%= link_to 'My urls', urls_path, :class => 'navbar-link' %> |
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to 'All urls', urls_path, :class => 'navbar-link' %> |
          <%= link_to 'Sign up', new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to 'Login', new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </header>

    <% if notice %>
      <p class="alert alert-notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-error"><%= alert %></p>
    <% end %>

    <%= yield %>

  </div>
</body>
</html>

app/views/urls/index.html.erb
<h1>Listing urls</h1>

<table>
  <thead>
    <tr>
      <th>Original</th>
      <th>Shortened</th>
      <th>Clicks</th>
      <th></th>
      <% if user_signed_in? %>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= url.original %></td>
        <td><%= polymorphic_url(:short, short: url.short) %></td>
        <td><%= url.clicks %></td>
        <td><%= link_to 'Info', polymorphic_url(:short, short: "#{url.short}+") %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Destroy', url, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<menu>
  <%= link_to 'Shorten a url', '/' %>
</menu>